# Generated by Django 2.2.1 on 2021-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=10)),
                ('teacher_age', models.IntegerField(max_length=100)),
                ('teacher_department', models.CharField(max_length=20)),
                ('teaxher_major', models.CharField(max_length=20)),
            ],
        ),
    ]
