# Generated by Django 2.2.1 on 2021-03-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_teacher_teacher_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='APIKEY',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_address',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_college',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_degree',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_height',
            field=models.CharField(default='无', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_hobby',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_ismarry',
            field=models.CharField(default='无', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_phone',
            field=models.CharField(default='无', max_length=11),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_salary',
            field=models.CharField(default='无', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_weight',
            field=models.CharField(default='无', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_department',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_major',
            field=models.CharField(default='无', max_length=20),
        ),
    ]
